// <auto-generated />
namespace CcAcca.LibraryMigrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ReplacemigrationSubclassLookupItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReplacemigrationSubclassLookupItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201505062002328_Replace migration - Subclass LookupItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
